[package]
name = "streammoney"
version = "0.1.1"
description = "streammoney.finance smart contract"
edition = "2018"

[dependencies]
solana-program = "1.7.1"

[dev-dependencies]
solana-program-test = "1.7.1"
solana-sdk = "1.7.1"

[lib]
crate-type = ["cdylib", "lib"]
